# Generated by Django 4.2.4 on 2023-08-16 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_namespaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="namespacepermission",
            options={"verbose_name": "NamespacePermissions"},
        ),
        migrations.AlterModelOptions(
            name="objectpermission",
            options={"verbose_name": "ObjectPermissions"},
        ),
        migrations.AlterField(
            model_name="namespacepermission",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_permissions",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="namespacepermission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="objectpermission",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_permissions",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="objectpermission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
