# Generated by Django 3.2.20 on 2023-08-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_namespace_permissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NamespacedExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_namespace_permissions.namespace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
